# Generated by Django 6.0.7 on 2026-07-18 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_plain_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='whatsapp_number',
        ),
    ]
