# Generated by Django 6.0.6 on 2026-07-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_storedfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="level",
            field=models.CharField(
                choices=[
                    ("iniciante", "Iniciante"),
                    ("intermediario", "Intermediário"),
                    ("avancado", "Avançado"),
                ],
                default="iniciante",
                max_length=20,
                verbose_name="Nível de Programação",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="whatsapp_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="WhatsApp (WAHA)"
            ),
        ),
    ]
