# Generated by Django 6.0.7 on 2026-07-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_user_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="plain_password",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Senha em Texto Plano",
            ),
        ),
    ]
