# Generated by Django 6.0.5 on 2026-05-29 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='conversation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='chatbot.conversation'),
        ),
    ]
